[project]
name = "yoloapi"
version = "0.1.0"
requires-python = ">=3.10"

dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "minio",
    "python-multipart",
    "pillow",
    "numpy",
    "opencv-python-headless",
    "ultralytics"
]

[tool.uv]
index-url = "https://pypi.tuna.tsinghua.edu.cn/simple"