# 单位信息配置文件
# 用于配置网站的基本信息、品牌信息等

# 组织信息
organization:
  name: "禾影千寻"           # 完整组织名称
  logo: "/image.png"       # Logo文件路径（放在 web/public 目录下）
  avatar: "/avatar.jpg"      # 头像文件路径（放在 web/public 目录下）
  login_bg: "/login-bg.jpg"  # 登录背景图片路径（放在 web/public 目录下）

# 项目信息
branding:
  name: "QianXun"
  title: "QianXun: 更智能的知识库智能体平台"     # 系统标题
  subtitle: "大模型驱动的知识库智能体平台"          # 副标题

features: []

actions:
  - name: "演示视频"
    icon: "video"
    url: "https://www.bilibili.com/video/BV1DF14BTETq"



# 页脚信息
footer:
  copyright: "© 禾影千寻 2026 v1.0.1 power by Yuxi"
